apiVersion: v1
kind: Service
metadata:
  name: vllm-mistral-sm4
  namespace: default
spec:
  type: NodePort
  selector:
    app: vllm-mistral-sm4
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30801
      protocol: TCP
