apiVersion: v1
kind: Namespace
metadata:
  name: dynamo-snapshot
  labels:
    app.kubernetes.io/managed-by: dynamo-snapshot-eks
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
