#!/usr/bin/env bash
# Deterministically emit a vLLM serving Pod manifest for one (parallelism shape × KV arm).
# Single-variable discipline: every manifest is byte-identical to the baseline EXCEPT the
# parallelism flags and the KV-arm flags, so the measured Δ is attributable (OPTIMIZATION-LOOP.md §3).
#
# Usage: gen-serving-manifest.sh <shape> <kv_arm>  > /tmp/vllm-<shape>-<arm>.yaml
#   shape : tp4 | tp4ep4 | tp2dp2 | tp4dp2 | tp2dp4
#   kv_arm: gpu-only | cpu-offload | nvme-tiering
#
# FP8 block-128 rule (lessons.md): TP must be in {1,2,4} (1536/TP %128==0). TP8 is INVALID.
# All shapes below keep TP in {2,4}. DP scales replicas across the node's 8 GPUs.
set -euo pipefail
SHAPE="${1:?shape}"; ARM="${2:?kv_arm}"

case "$SHAPE" in
  tp4)    TP=4; DP=1; EP="";                       GPUS=4 ;;
  tp4ep4) TP=4; DP=1; EP="--enable-expert-parallel"; GPUS=4 ;;  # DP-less EP: gave +40% on 0.19, REGRESSED on 0.23
  tp2dp2) TP=2; DP=2; EP="";                       GPUS=4 ;;
  tp4dp2) TP=4; DP=2; EP="";                       GPUS=8 ;;
  tp2dp4) TP=2; DP=4; EP="";                       GPUS=8 ;;
  # EP-VIA-DP: the current-vLLM EP path (docs: EP_SIZE = TP×DP, benefit comes via DP + --enable-expert-parallel
  # TOGETHER). We previously ran DP shapes WITHOUT --enable-expert-parallel (EP=""), and EP WITHOUT DP (tp4ep4) —
  # never the combination that current vLLM actually optimizes. These are the docs' single-node recipe.
  tp1dp4ep) TP=1; DP=4; EP="--enable-expert-parallel"; GPUS=4 ;;  # docs' exact single-node EP recipe (TP1×DP4)
  tp2dp2ep) TP=2; DP=2; EP="--enable-expert-parallel"; GPUS=4 ;;  # TP2×DP2 EP fallback if TP1 attn-replication OOMs
  *) echo "bad shape: $SHAPE" >&2; exit 2 ;;
esac

# KV-arm flags. gpu-only = APC only (baseline). cpu-offload uses the OffloadingConnector via
# --kv-transfer-config ONLY. CONFIRMED against vLLM source (v1/kv_offload/cpu.py, factory.py):
#   * There is NO --kv_offloading_backend / --kv_offloading_size CLI flag — those were bogus and
#     CRASHED engine-init (2026-06-30 P1: both offload arms died at "Engine core initialization failed").
#   * CPUOffloadingSpec reads ONLY kv_connector_extra_config.num_cpu_blocks (+ optional block_size).
#   * NVMe/disk tiering is NOT supported by the stock connector — only "CPUOffloadingSpec" is registered
#     in OffloadingSpecFactory; mediums are GPU/CPU only. nvme_path/num_nvme_blocks are SILENTLY IGNORED.
#     A disk KV tier needs LMCache or Mooncake, not the stock OffloadingConnector. So nvme-tiering is
#     ERROR'd here rather than emitting a config that pretends to tier to disk.
# The connector must NOT silently disable chunked prefill — the runner asserts enable_chunked_prefill
# stays True post-startup (known offload regression).
KV_FLAGS=""
# v0.23 OffloadingConnector schema (CONFIRMED against vLLM v0.23.0 source, 2026-06-30 — the engine
# REQUIRES these exact keys; a real boot failed with "cpu_bytes_to_use must be specified"):
#   * CPU tier (cpu/spec.py): kv_connector_extra_config.cpu_bytes_to_use = BYTES (NOT num_cpu_blocks —
#     that was the v0.11 key; the schema changed). Optional block_size, eviction_policy(lru|arc).
#   * NVMe/disk tier (tiering/spec.py): IS supported in 0.23 via spec_name="TieringOffloadingSpec" +
#     secondary_tiers:[{type:"fs", root_dir:<path>}] (FileSystemTierManager). (My earlier "nvme unsupported"
#     was from reading v0.11 source — WRONG for 0.23. Registered tiers: example, fs, obj.)
# Sizing: cpu_bytes_to_use=200GiB (node has ~2TB RAM; comfortably holds overflow beyond the GPU KV pool).
CPU_BYTES=214748364800   # 200 GiB
case "$ARM" in
  gpu-only) ;;  # nothing extra; APC already on (this is the customer's config MINUS the offload flags)
  cpu-offload)
    KV_FLAGS='--kv-transfer-config '"'"'{"kv_connector":"OffloadingConnector","kv_role":"kv_both","kv_connector_extra_config":{"cpu_bytes_to_use":'"${CPU_BYTES}"'}}'"'"' '
    ;;
  nvme-tiering)
    KV_FLAGS='--kv-transfer-config '"'"'{"kv_connector":"OffloadingConnector","kv_role":"kv_both","kv_connector_extra_config":{"spec_name":"TieringOffloadingSpec","cpu_bytes_to_use":'"${CPU_BYTES}"',"secondary_tiers":[{"type":"fs","root_dir":"/mnt/nvme/kv-cache"}]}}'"'"' '
    ;;
  *) echo "bad kv_arm: $ARM" >&2; exit 2 ;;
esac

DP_FLAG=""
[ "$DP" -gt 1 ] && DP_FLAG="--data-parallel-size $DP"

NAME="vllm-${SHAPE}-${ARM}"

cat <<YAML
# AUTO-GENERATED by gen-serving-manifest.sh — shape=${SHAPE} kv_arm=${ARM} (TP=${TP} DP=${DP} GPUs=${GPUS})
# Single-variable vs baseline: only parallelism + KV-arm flags differ.
apiVersion: v1
kind: Pod
metadata:
  name: ${NAME}
  namespace: default
  labels: {app: vllm-minimax-m2, shape: "${SHAPE}", kv_arm: "${ARM}"}
spec:
  restartPolicy: Never
  nodeSelector: {blueprint: minimax-m2}
  tolerations:
    - {key: ai-infra/b200, operator: Exists, effect: NoSchedule}
    - {key: nvidia.com/gpu, operator: Exists, effect: NoSchedule}
  hostNetwork: true
  containers:
    - name: vllm
      image: vllm/vllm-openai:v0.23.0          # STOCK v0.23.0 — exactly the customer's known-good image
      command:
        - bash
        - -c
        - |
          mkdir -p /mnt/nvme/kv-cache
          # Cache-wipe guards the transformers_modules poisoning (#35570) on reused spot nodes; harmless on a fresh one.
          rm -rf /mnt/nvme/hf-cache/modules/transformers_modules 2>/dev/null || true
          M=/mnt/nvme/models/minimax-m2
          # INTEGRITY REPAIR (root cause, proven on a g6e CPU probe 2026-06-30): stock v0.23 loads M2 fine
          # from a COMPLETE dir; the B200 boots failed because the staged copy was missing the small
          # config/tokenizer/code files (partial stage), forcing a slow→fast tokenizer convert that errors.
          # Re-fetch the small files (NOT the 214GB weights) and verify before serving. Fail loud if still missing.
          python3 - <<'PYEOF' || { echo "FATAL: model config/tokenizer repair failed"; exit 1; }
          import os
          from huggingface_hub import snapshot_download
          snapshot_download("MiniMaxAI/MiniMax-M2",
              allow_patterns=["*.json","*.txt","*.py","*token*","config*","generation_config*","*.model"],
              local_dir="/mnt/nvme/models/minimax-m2")
          need=["config.json","tokenizer.json","tokenizer_config.json","configuration_minimax_m2.py"]
          miss=[f for f in need if not os.path.exists(f"/mnt/nvme/models/minimax-m2/{f}")]
          assert not miss, f"missing after repair: {miss}"
          print("[repair] config+tokenizer+code present:", need)
          PYEOF
          ln -sfn /mnt/nvme/models/minimax-m2 /mnt/nvme/models/minimax_m2
          # REPLICATE the customer's KNOWN-GOOD v0.23 launch EXACTLY (their config boots M2 on H200).
          # Do NOT add flags they don't use (--compilation-config / --max-model-len / --served-model-name
          # were OUR divergence and the likely cause of the AutoTokenizer break). Reasoning parser is
          # minimax_m2 (NOT _append_think). The shape (TP/DP/EP) + KV-arm flags are the ONLY single-variable deltas.
          exec python3 -m vllm.entrypoints.openai.api_server \\
            --model /mnt/nvme/models/minimax_m2 \\
            --served-model-name MiniMax-M2 \\
            --trust-remote-code \\
            --tensor-parallel-size ${TP} ${DP_FLAG} ${EP} \\
            --gpu-memory-utilization 0.95 \\
            --enable-prefix-caching \\
            --enable-chunked-prefill \\
            --max-num-seqs 512 \\
            --max-num-batched-tokens 131072 \\
            --kv-cache-dtype fp8 \\
            --moe-backend triton \\
            --linear-backend cutlass \\
            --tool-call-parser minimax_m2 \\
            --enable-auto-tool-choice \\
            --reasoning-parser minimax_m2 \\
            ${KV_FLAGS}--host 0.0.0.0 --port 8000
      env:
        - {name: SAFETENSORS_FAST_GPU, value: "1"}
        - {name: HF_HOME, value: /mnt/nvme/hf-cache}
        - {name: VLLM_CACHE_ROOT, value: /root/.cache/vllm}
        - name: HF_TOKEN
          valueFrom: {secretKeyRef: {name: hf-token, key: token}}
      resources:
        requests: {nvidia.com/gpu: "${GPUS}", cpu: "32", memory: 256Gi}
        limits:   {nvidia.com/gpu: "${GPUS}", cpu: "64", memory: 512Gi}
      securityContext: {capabilities: {add: ["IPC_LOCK"]}}
      volumeMounts:
        - {name: nvme, mountPath: /mnt/nvme, mountPropagation: HostToContainer}
        - {name: vllm-cache, mountPath: /root/.cache/vllm}
        - {name: shm, mountPath: /dev/shm}
      readinessProbe:
        httpGet: {path: /health, port: 8000}
        initialDelaySeconds: 120
        periodSeconds: 15
        failureThreshold: 200      # ~50 min grace — M2 first boot is ~35-40 min (lessons.md)
  volumes:
    - {name: nvme, hostPath: {path: /mnt/nvme, type: Directory}}
    - {name: vllm-cache, hostPath: {path: /mnt/nvme/vllm-cache, type: DirectoryOrCreate}}
    - {name: shm, emptyDir: {medium: Memory, sizeLimit: 64Gi}}
YAML
