#!/usr/bin/env bash
# Deterministically emit a vLLM serving Pod manifest for one (parallelism shape × KV arm).
# Single-variable discipline: every manifest is byte-identical to the baseline EXCEPT the
# parallelism flags and the KV-arm flags, so the measured Δ is attributable (OPTIMIZATION-LOOP.md §3).
#
# Usage: gen-serving-manifest.sh <shape> <kv_arm>  > /tmp/vllm-<shape>-<arm>.yaml
#   shape : tp4 | tp4ep4 | tp2dp2 | tp4dp2 | tp2dp4
#   kv_arm: gpu-only | cpu-offload | nvme-tiering
#
# FP8 block-128 rule (lessons.md): TP must be in {1,2,4} (1536/TP %128==0). TP8 is INVALID.
# All shapes below keep TP in {2,4}. DP scales replicas across the node's 8 GPUs.
set -euo pipefail
SHAPE="${1:?shape}"; ARM="${2:?kv_arm}"

case "$SHAPE" in
  tp4)    TP=4; DP=1; EP="";                       GPUS=4 ;;
  tp4ep4) TP=4; DP=1; EP="--enable-expert-parallel"; GPUS=4 ;;
  tp2dp2) TP=2; DP=2; EP="";                       GPUS=4 ;;
  tp4dp2) TP=4; DP=2; EP="";                       GPUS=8 ;;
  tp2dp4) TP=2; DP=4; EP="";                       GPUS=8 ;;
  *) echo "bad shape: $SHAPE" >&2; exit 2 ;;
esac

# KV-arm flags. gpu-only = APC only (baseline). cpu-offload / nvme use the KVConnector
# (OffloadingConnector). The connector must NOT silently disable chunked prefill — the
# runner asserts enable_chunked_prefill stays True post-startup (known offload regression).
KV_FLAGS=""
case "$ARM" in
  gpu-only) ;;  # nothing extra; APC already on
  cpu-offload)
    KV_FLAGS='--kv-transfer-config '"'"'{"kv_connector":"OffloadingConnector","kv_role":"kv_both","kv_connector_extra_config":{"num_cpu_blocks":80000}}'"'"' '
    ;;
  nvme-tiering)
    KV_FLAGS='--kv-transfer-config '"'"'{"kv_connector":"OffloadingConnector","kv_role":"kv_both","kv_connector_extra_config":{"num_cpu_blocks":40000,"nvme_path":"/mnt/nvme/kv-cache","num_nvme_blocks":200000}}'"'"' '
    ;;
  *) echo "bad kv_arm: $ARM" >&2; exit 2 ;;
esac

DP_FLAG=""
[ "$DP" -gt 1 ] && DP_FLAG="--data-parallel-size $DP"

NAME="vllm-${SHAPE}-${ARM}"

cat <<YAML
# AUTO-GENERATED by gen-serving-manifest.sh — shape=${SHAPE} kv_arm=${ARM} (TP=${TP} DP=${DP} GPUs=${GPUS})
# Single-variable vs baseline: only parallelism + KV-arm flags differ.
apiVersion: v1
kind: Pod
metadata:
  name: ${NAME}
  namespace: default
  labels: {app: vllm-minimax-m2, shape: "${SHAPE}", kv_arm: "${ARM}"}
spec:
  restartPolicy: Never
  nodeSelector: {blueprint: minimax-m2}
  tolerations:
    - {key: ai-infra/b200, operator: Exists, effect: NoSchedule}
    - {key: nvidia.com/gpu, operator: Exists, effect: NoSchedule}
  hostNetwork: true
  containers:
    - name: vllm
      image: vllm/vllm-openai:minimax27
      command:
        - bash
        - -c
        - |
          mkdir -p /mnt/nvme/kv-cache
          exec python3 -m vllm.entrypoints.openai.api_server \\
            --model /mnt/nvme/models/minimax-m2 \\
            --served-model-name MiniMax-M2 \\
            --tensor-parallel-size ${TP} ${DP_FLAG} ${EP} \\
            --moe-backend triton \\
            --tool-call-parser minimax_m2 \\
            --reasoning-parser minimax_m2_append_think \\
            --enable-auto-tool-choice \\
            --enable-prefix-caching \\
            --kv-cache-dtype fp8 \\
            --max-model-len 196608 \\
            --gpu-memory-utilization 0.90 \\
            ${KV_FLAGS}--compilation-config '{"mode":3,"pass_config":{"fuse_minimax_qk_norm":true}}' \\
            --trust-remote-code \\
            --host 0.0.0.0 --port 8000
      env:
        - {name: VLLM_USE_FLASHINFER_MOE_FP8, value: "0"}
        - {name: SAFETENSORS_FAST_GPU, value: "1"}
        - {name: VLLM_USE_V1, value: "1"}
        - {name: HF_HOME, value: /mnt/nvme/hf-cache}
        - {name: VLLM_CACHE_ROOT, value: /root/.cache/vllm}
        - name: HF_TOKEN
          valueFrom: {secretKeyRef: {name: hf-token, key: token}}
      resources:
        requests: {nvidia.com/gpu: "${GPUS}", cpu: "32", memory: 256Gi}
        limits:   {nvidia.com/gpu: "${GPUS}", cpu: "64", memory: 512Gi}
      securityContext: {capabilities: {add: ["IPC_LOCK"]}}
      volumeMounts:
        - {name: nvme, mountPath: /mnt/nvme, mountPropagation: HostToContainer}
        - {name: vllm-cache, mountPath: /root/.cache/vllm}
        - {name: shm, mountPath: /dev/shm}
      readinessProbe:
        httpGet: {path: /health, port: 8000}
        initialDelaySeconds: 120
        periodSeconds: 15
        failureThreshold: 200      # ~50 min grace — M2 first boot is ~35-40 min (lessons.md)
  volumes:
    - {name: nvme, hostPath: {path: /mnt/nvme, type: Directory}}
    - {name: vllm-cache, hostPath: {path: /mnt/nvme/vllm-cache, type: DirectoryOrCreate}}
    - {name: shm, emptyDir: {medium: Memory, sizeLimit: 64Gi}}
YAML
